Selecro/Selecro-webovky

- src/app/pages/navody/navody.component.css
- src/app/pages/navody/navody.component.html
- src/app/pages/vyukovymod/vyukovymod.component.css
- src/app/pages/vyukovymod/vyukovymod.component.html
Castecna responzivita navodu. Div jsem musel zamenit za ng-container, protoze mi div rozhazoval pozice bunek.
> Responzivita navody

- src/app/pages/navody/navody.component.css
- src/app/pages/vyukovymod/vyukovymod.component.css
- src/app/pages/vyukovymod/vyukovymod.component.html
Responzivita vyukoveho modu. Funguje na stejnem principu jak navody. Oddelal jsem popis lehke, stredni a tezke, kdyztak se tam potom doplni legenda podle barev popripadne filtr ale to asi az pozdeji.
> Responzivita vyukovy mod

- src/app/pages/navody/navody.component.css
- src/app/pages/slovnik/slovnik.component.css
- src/app/pages/slovnik/slovnik.component.html
- src/app/pages/vyukovymod/vyukovymod.component.css
- src/app/pages/vyukovymod/vyukovymod.component.html
Castecna responzivita slovniku.
> Responzivita slovnik

- src/app/pages/pomucky/pomucky.component.css
- src/app/pages/pomucky/pomucky.component.html
Oprava css v pomuckach. Video se bude muset jeste poupravit (na mobilech to nevypada nejlip).
> pomucky oprava

- src/app/pages/home/home.component.css
- src/app/pages/home/home.component.html
- src/app/pages/pomucky/pomucky.component.css
- src/app/pages/pomucky/pomucky.component.html
- src/app/pages/slovnik/slovnik.component.css
Responzivni text - slovnik, home
> Responzivni text

- src/app/app.component.css
- src/app/app.component.html
- src/app/pages/home/home.component.css
- src/app/pages/home/home.component.html
- src/app/pages/navody/navody.component.css
- src/app/pages/pomucky/pomucky.component.css
- src/app/pages/pomucky/pomucky.component.html
- src/app/pages/slovnik/slovnik.component.css
- src/app/pages/slovnik/slovnik.component.html
- src/app/pages/vyukovymod/vyukovymod-detail/vyukovymod-detail.component.css
- src/app/pages/vyukovymod/vyukovymod-detail/vyukovymod-detail.component.html
- src/app/pages/vyukovymod/vyukovymod.component.css
Oprava posouvaciho backgroundu kdyz se prepinalo mezi pages.
> Oprava posouvaci background

- src/app/app.component.css
- src/app/pages/navody/navody-detail/navody-detail.component.css
- src/app/pages/navody/navody-detail/navody-detail.component.html
Lupa s textem hledat nejsou uprostred
> Menu oprava

- .github/workflows/main.yml
- .htaccess
- package-lock.json
Implemented deploying dev branch to develop.selecro.cz subdomain.
> Added new CI

- src/app/pages/navody/navody-detail/navody-detail.component.css
- src/app/pages/navody/navody-detail/navody-detail.component.html
> navody detail css

- src/app/app.component.css
- src/app/pages/pomucky/pomucky.component.css
- src/app/pages/pomucky/pomucky.component.html
Srovnani videa s bublinami. Uprava velikosti videa, responzivita.
> pomucky video

- src/app/pages/vyukovymod/vyukovymod-detail/vyukovymod-detail.component.css
- src/app/pages/vyukovymod/vyukovymod-detail/vyukovymod-detail.component.html
oprava videa, responzivita - vyukovy mod
> vyukovy mod video

- src/app/pages/home/home.component.css
stejna velikost pinterest loga
> pinterest fix

- src/app/pages/slovnik/slovnik.component.css
responzivni znacka a zkratka ve slovniku
> responzivni img

- src/app/pages/vyukovymod/vyukovymod-detail/vyukovymod-detail.component.css
> vyukovymod detail fix

- src/app/app.component.css
- src/app/app.component.html
> vraceni listy

- src/app/app.component.css
- src/app/app.component.html
- src/app/pages/home/home.component.css
Hamburger button se zobrazi na urcitem poctu pixelu a bloky v menu zmizi.
> zobrazeni buttonu pro sidenav

- src/app/app.component.css
- src/app/app.component.html
- src/app/app.component.ts
Nav se otevira zvrchu pod listou. Text je s ikonami je vlevo. Sirka je 100%
> uprava nav

- src/app/pages/vyukovymod/vyukovymod-detail/vyukovymod-detail.component.css
Sipky s krokama jsou na stredu
> kroky center

- src/app/pages/navody/navody-detail/navody-detail.component.css
- src/app/pages/navody/navody-detail/navody-detail.component.html
Buttons v navodech (next, timer, hotovo) nebyly responzivni
> buttons responzivita

- src/app/pages/pomucky/pomucky.component.css
- src/app/pages/pomucky/pomucky.component.html
Odstraneni cary, text vlevo, obrazky vpravo
> upravy - pomucky

- src/app/pages/slovnik/slovnik.component.css
- src/app/pages/slovnik/slovnik.component.html
Nadpis na stred, zmenseni textu
> Slovnik - upravy

- src/app/app.component.css
- src/app/app.component.html
> Searching css

- src/app/pages/prihlaseni/prihlaseni.component.css
- src/app/pages/prihlaseni/prihlaseni.component.html
- src/app/pages/registrace/registrace.component.css
> prihlaseni, registrace
